### ISSUE TITLE
Project purpose / description, and data safety

### ISSUE THREAD

**Issue by shah-in-boots** [nprave3/TTE-Data-Extraction#1]
Hello, you've added me to this repository as a collaborator. Please confirm that...

- [x] there is no identifying information in the datasets uploaded to this repository
- [x] the code contains no PHI in comments
- [x] there is a descriptive or useful readme to help with collaborators

**Comment by nprave3** [comment]
- no identifying information in the datasets uploaded to this repository
- code contains no PHI in comments
- there is a descriptive or useful readme to help with collaborators
